services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    image: cmc-autox-work-api-dev
    entrypoint:
      - flask
      - run
      - --debug
      - --host=0.0.0.0
    volumes:
      - ./api/instance:/app/instance
      - ./api:/app
      - ./results:/app/results
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - CMC_CONFIG=config.cfg
  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: cmc-autox-work-client-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
