services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    image: cmc-autox-work-api
    volumes:
      - ./api/instance:/app/instance
      - ./api/config.cfg:/app/config.cfg
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - CMC_CONFIG=config.cfg
  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: cmc-autox-work-client
    volumes:
      - /etc/letsencrypt/live/devinmackenzie.com/fullchain.pem:/etc/nginx/fullchain.pem
      - /etc/letsencrypt/live/devinmackenzie.com/privkey.pem:/etc/nginx/privkey.pem
    ports:
      - "443:443"
