services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    image: cmc-autox-work-api-prod
    volumes:
      - ./api/instance:/app/instance
      - ./api/config.cfg:/app/config.cfg
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - CMC_CONFIG=config.cfg
